security:
    password_hashers:
        App\Security\User:
            algorithm: auto

    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
#            entity:
#                class: App\Security\User
#                property: login
            id: App\Security\UserProvider
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
#            login_throttling:
#                max_attempts: 5
#                interval: '10 minutes'

            logout:
                path: app_logout
                
            json_login:
                check_path: app_login
                username_path: login
                password_path: password
#            lazy: true
#            provider: app_user_provider
#            custom_authenticators:
#                - App\Security\ApiKeyAuthenticator


    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
