vich_uploader:
    db_driver: orm
    storage: flysystem
        
    mappings:
        media_object:
            uri_prefix: /media/img
            upload_destination: digitalocean.storage
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
