# Default values for api-platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

php:
  image:
    repository: "registry.digitalocean.com/wowvendor/blog/php"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  replicaCount: 1
  appEnv: prod
  appDebug: "0"
  appSecret: ""
  corsAllowOrigin: "^https://blog\\.feature\\.zone|https://dev\\.feature\\.zone|http://localhost:3000$"
  trustedHosts: "^127\\.0\\.0\\.1|localhost|api-platform|.*\\.feature\\.zone$"
  trustedProxies:
    - "127.0.0.1"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"



nginx:
  image:
    repository: "registry.digitalocean.com/wowvendor/blog/nginx"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  # If you use Mercure, you need the managed or the On Premise version to deploy more than one pod: https://mercure.rocks/docs/hub/cluster
  replicaCount: 1

# You may prefer using the managed version in production: https://mercure.rocks
mercure:
  publishUrl: ""
  subscribeUrl: https://blog.feature.zone/.well-known/mercure
  # Change me!
  jwtToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOltdfX0.Oo0yg7y4yMa1vr_bziltxuTCqb8JVHKxp-f_FwwOim0"
  # Change me/!
  publisherJwtKey: "!ChangeMe!"
  # Change me!
  subscriberJwtKey: "!ChangeMe!"

mysql:
  name: mysql
  ip: 10.110.0.7
  port: 3206
  Username: "hide"
  Password: "hide"
  Database: "blogapi"

imagePullSecrets: 
  - name: registry-wowvendor
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '800'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '800'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '800'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: blog.feature.zone
      paths:
        - /api
  tls:
   - secretName: echo-tls
     hosts:
       - blog.feature.zone

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 100m
     memory: 228Mi
   requests:
     cpu: 100m
     memory: 228Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
