 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
     name: "s3proxy"
     annotations:
         kubernetes.io/ingress.class: "nginx"
         nginx.ingress.kubernetes.io/rewrite-target: /
         cert-manager.io/cluster-issuer: "letsencrypt-prod"
 spec:
   tls:
   - hosts:
      - blog.wowvendor.com
     secretName: echo-tls
   rules:
   - host: /
     http:
       paths:
       - path:
         backend:
           serviceName: "s3proxy"
           servicePort: 80
