apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-platform.fullname" . }}
  labels:
    {{- include "api-platform.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ printf "mysql://%s:%s@%s:%s/%s?serverVersion=8.0.19" .Values.mysql.Username .Values.mysql.Password .Values.mysql.name ( .Values.mysql.port |toString) .Values.mysql.Database | b64enc | quote }}
  php-app-secret: {{ .Values.php.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.mercure.jwtSecret | default (randAlphaNum 40) | b64enc | quote }}
